### ISSUE TITLE
Error lyrics command

### ISSUE THREAD

**Issue by razvandamian** [VeguiIzumi/NezumiYuiV.2#3]
TypeError: Cannot read property 'result' of undefined
2020-08-16T20:41:01.136517+00:00 app[worker.1]:     at LyricsCommand.run (/app/commands/music/lyrics.js:56:46)
2020-08-16T20:41:01.136519+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2020-08-16T20:41:01.136521+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-16T20:41:01.136532+00:00 app[worker.1]:     at async CommandoMessage.run (/app/node_modules/discord.js-commando/src/extensions/message.js:235:20)
2020-08-16T20:41:01.136532+00:00 app[worker.1]:     at async CommandDispatcher.handleMessage (/app/node_modules/discord.js-commando/src/dispatcher.js:143:19)

**Comment by VeguiIzumi** [comment]
what are you trying to find to get this error ?, because i never got this error

**Comment by razvandamian** [comment]
dk, i just type (prefix)lyrics the song name and sometimes i get this error
